apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumi-prod-ing
  annotations:
    cert-manager.io/cluster-issuer: "lumi-backend-prod-clusterissuer"
    spec.ingressClassName: "public"
spec:
  tls:
  - hosts:
    - lumi-api-v1.leandrodamasio.com
    secretName: lumi-secret
  rules:
  - host: lumi-api-v1.leandrodamasio.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lumi-backend-node-prod-svc
            port:
              number: 3000
