apiVersion: v1
kind: Service
metadata:
  name: lumi-backend-node-prod-svc
spec:
  selector:
    app: lumi-backend-node-prod-deploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
