apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gph-frontend-prod-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ldamasio@gmail.com
    privateKeySecretRef:
      name: account-key-staging
    solvers:
    - http01:
       ingress:
         class: nginx
