apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbx-backend-api-gateway-django-prod-deploy
spec:
  selector:
    matchLabels:
      app: rbx-backend-api-gateway-django-prod-deploy
  template:
    metadata:
      labels:
        app: rbx-backend-api-gateway-django-prod-deploy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: rbx-backend-api-gateway-django-prod-deploy
          image: ldamasio/cro-backend-django-prod:latest
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: "backend.settings"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: SECRET_KEY
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rbx-backend-api-gateway-prod-secret
                key: DB_PASSWORD
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "1000Mi"
              cpu: "750m"
            limits:
              memory: "1000Mi"
              cpu: "1500m"
