apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbx-access
  namespace: rbx
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["pods", "services", "deployments", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]