apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbx
  name: acesso-pods
rules:
- apiGroups: [""] # "" indica o core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
